[extend]
useDefault = true

[allowlist]
regexes = ["sk_test_4eC39HqLyjWDarjtT1zdp7dc"]
paths = [
  '''^src/components/mock\.js$''',
  '''^openapi\.yaml$''',
  '''^src/openapi/traefik-api\.yaml$''',
  '''^src/schemas/balancer-api\.ts$''',
  '''^src/components/BalancerApiButton\.tsx$''',
  '''^src/constants/apiButtonInfo\.ts$'''
]