/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/gateways": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List of ALB Gateways
		 * @description By sending request to this endpoint you can get list of ALB Gateways which are currently attached to account network infrastructure (VPC).
		 *     Role-based access:
		 *       - `admin` role in`operator` account see all gateways of all accounts
		 *       - `admin`/`owner`, `member` roles see gateways in attached to account
		 *
		 */
		get: operations["alb_list"];
		put?: never;
		/**
		 * Attach new ALB Gateway to account infrastructure
		 * @description This endpoint is called from CloudGateway Automation only. So we are not going to provide ability to Account Admins to create new gateways
		 *     Role-based access:
		 *       - `operator` role can send requests to the endpoint
		 *       - other roles does have to access the endpoint
		 *
		 */
		post: operations["alb_attach"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/gateways/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Display ALB gateway details
		 * @description Role-based access:
		 *       - `admin` role in`operator` account see all gateways of all accounts
		 *       - `admin`/`owner`, `member` roles see gateways in attached to account
		 *
		 */
		get: operations["alb_show"];
		/**
		 * Update Traefik Gateway. Usually use to assign Traefik Gateway to account.
		 * @description Role-based access:
		 *       - `operator` role can send requests to the endpoint
		 *       - other roles does have to access the endpoint
		 *
		 */
		put: operations["alb_modify"];
		post?: never;
		/**
		 * Remove Traefik Gateway (un-register)
		 * @description This endpoint is called from CloudGateway Automation only. So we are not going to provide ability to Account Admins to delete gateways
		 *     Role-based access:
		 *       - `operator` role can send requests to the endpoint
		 *       - other roles does have to access the endpoint
		 *
		 */
		delete: operations["alb_unregister"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/gateways/{uuid}/config": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Return YAML config for Traefik Gateway
		 * @description This endpoint is called from CloudGateway Automation only. So we are not going to provide ability to Account Admins to see a Gateway Config
		 *
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Used for simplified authorization for some internal requests from CloudGateway to config.
					 *      */
					uuid: components["parameters"]["CloudGatewayId"];
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Operation successful */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						"text/yaml": components["schemas"]["GatewayConfig"];
					};
				};
				404: components["responses"]["not_found"];
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/certificates": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List of certificates attached to an account gateways
		 * @description This endpoint is called to retrieve the list of certificates attached to an account's gateways.
		 *     Role-based access:
		 *       - `operator` role can see all certificates in location
		 *       - `admin`/`owner` role can see all certificates in account
		 *       - `member` role can see only own certificates
		 *
		 */
		get: operations["certificates_list"];
		put?: never;
		/**
		 * Create a new certificate
		 * @description This endpoint is used for creating a new SSL certificate and uploading it to a **CloudGateway**. The server automatically checks the validity of the uploaded certificate. After the certificate has been successfully uploaded via the API, CloudGateway Automation automatically downloads and applies it to a route defined in the hostnames field.
		 *     Role-based access:
		 *       - `operator` role can create certificate in any account per location
		 *       - `admin`/`owner` role can create certificate only in the account space
		 *       - `member` role can create certificate only in the account space
		 *
		 */
		post: operations["certificates_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/certificates/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Show certificate record
		 * @description This endpoint is used to explore the details of a certificate.
		 *     Role-based access:
		 *       - `operator` role can see all certificates in location
		 *       - `admin`/`owner` role can see all certificates in account
		 *       - `member` role can see only own certificates
		 *
		 */
		get: operations["certificate_show"];
		/**
		 * update cert
		 * @description The endpoint is called for updating a certificate. The server automatically checks the validity of the updated certificate. After the certificate has been successfully updated via the API, CloudGateway Automation automatically downloads and applies it to a route defined in the hostnames field.
		 *     Role-based access:
		 *       - `operator` role can manage all certificates in location
		 *       - `admin`/`owner` role can manage all certificates in account
		 *       - `member` role can manage only own certificates
		 *
		 */
		put: operations["certificate_update"];
		post?: never;
		/**
		 * Delete certificate
		 * @description The endpoint is called to delete a certificate from the system.
		 *     Role-based access:
		 *       - `operator` role can manage all certificates in location
		 *       - `admin`/`owner` role can manage all certificates in account
		 *       - `member` role can manage only own certificates
		 *
		 */
		delete: operations["certificate_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/services": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Show all existing certificates
		 * @description This endpoint is called to retrieve the list of services along with information about VMs' IP addresses. It is typically used for fetching the service_id when users create routes using the API. The information is synchronized with the Compute application automatically every 15 minutes.
		 *     Role-based access:
		 *       - `operator` role can see all services in the location
		 *       - `admin`/`owner` role can see all services in account
		 *       - `member` role can see only own services
		 *
		 */
		get: operations["services_list"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/routes": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get info about existing routes
		 * @description Role-based access:
		 *       - `operator` role can see all routes in the location
		 *       - `admin`/`owner` role can see all routes in account
		 *       - `member` role can see only own routes
		 *
		 */
		get: operations["routes_list"];
		put?: never;
		/**
		 * Create a new route
		 * @description Role-based access:
		 *       - `operator` role can create routes in any account per location
		 *       - `admin`/`owner` role can create route only in the account space
		 *       - `member` role can create route only in the account space
		 *
		 */
		post: operations["route_create"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/routes/{id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Show info about selected route
		 * @description Role-based access:
		 *       - `operator` role can see all routes in the location
		 *       - `admin`/`owner` role can see all routes in account
		 *       - `member` role can see only own routes
		 *
		 */
		get: operations["route_show"];
		/**
		 * Add routes
		 * @description Role-based access:
		 *       - `operator` role can modify all routes in the location
		 *       - `admin`/`owner` role can  modify routes in the account space
		 *       - `member` role can modify only own routes
		 *
		 */
		put: operations["route_update"];
		post?: never;
		/**
		 * Delete route
		 * @description Role-based access:
		 *       - `operator` role can delete each route in the location
		 *       - `admin`/`owner` role can delete routes only in the account space
		 *       - `member` role can delete only own routes
		 *
		 */
		delete: operations["route_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		error: {
			/**
			 * @description HTTP code
			 * @example 500
			 */
			readonly status: number;
			data: {
				/**
				 * @description Error message description. Shown in UI as is, so make sure it understandable by ordinary user.
				 * @example Server error
				 */
				readonly message?: string;
			};
		};
		GatewayCollection: components["schemas"]["Gateway"][];
		Gateway: {
			/** @example 1234 */
			readonly id?: number;
			/**
			 * @description Name of gateway. No real technical restriction on names Validate: alphanumeric/dash/underscore
			 *
			 * @example vpn-default
			 */
			name: string;
			/**
			 * @description UUID of CloudGateway VM on which traefik is deployed.
			 *     Stored in field 'uuid' in database.
			 *
			 * @example a843bf2a-7dac-4256-b048-cc1bc0864ccb
			 */
			cloudgw_id: string;
			/**
			 * @description Calculated field: cloudgw-<short_cloudgw_id> shows on which VM this VPN gateway is running
			 *
			 * @example cloudgw-a843bf2a
			 */
			readonly cloudgw_instance?: string;
			/**
			 * @description Account the ALB Gateway is attached
			 *
			 * @example devel
			 */
			account?: string;
			/**
			 * @description Timestamp object created
			 * @example 2023-10-23T12:00:00.136Z
			 */
			created_at?: string;
			/**
			 * @description Timestamp object updated
			 * @example 2023-11-23T18:00:01.555Z
			 */
			updated_at?: string;
		};
		Gateway_PUT: {
			/** @example alb-special */
			name?: string;
			/** @example devel */
			account?: string;
		};
		/**
		 * @description Traefik YAML config
		 * @example http:
		 *       routers:
		 *         SERVICE-http:
		 *           entryPoints:
		 *           - web
		 *           service: SERVICE
		 *           middlewares: SERVICE-redirect
		 *           rule: Host(`SERVICE.LOC.icdc.io`)
		 *         SERVICE-https:
		 *           entryPoints:
		 *           - websecure
		 *           service: SERVICE
		 *           rule: Host(`SERVICE.LOC.icdc.io`)
		 *           tls:
		 *             certResolver: default
		 *       middlewares:
		 *         SERVICE-redirect:
		 *           redirectscheme:
		 *             scheme: https
		 *       services:
		 *         SERVICE:
		 *           loadBalancer:
		 *             servers:
		 *             - url: http://10.254.20.10
		 *     tcp: {}
		 *     tls: {}
		 *
		 */
		GatewayConfig: string;
		CertificateCollection: components["schemas"]["Certificate"][];
		Certificate: {
			/** @example 5 */
			id?: number;
			/** @example test_acc1 */
			cert_path: string;
			/** @example test */
			key_path: string;
			/** @example null */
			ca_path: string;
			/** @example test */
			dest_ca_path: string;
			/** @example user@test.email */
			owner?: string;
			/** @example lb.computedev.loc.icdc.io */
			name?: string;
			values: {
				/** @example -----BEGIN CERTIFICATE-----
				 *     MIIGIDCCBAigAwIBAgIUMzFmSJ1zWSys9mqGaK8yjOpXffcwDQYJKoZIhvcNAQEL
				 *     BQAwgZYxCzAJBgNVBAYTAlJCMQ4wDAYDVQQIDAVNaW5zazEOMAwGA1UEBwwFTWlu
				 *     c2sxHDAaBgNVBAoME0RlZmF1bHQgQ29tcGFueSBMdGQxIjAgBgNVBAMMGWxiLmNv
				 *     bXB1dGVkZXYuemJ5LmljZGMuaW8xJTAjBgkqhkiG9w0BCQEWFmFocmVjaHVzaGtp
				 *     bkBnbWFpbC5jb20wHhcNMjExMDI4MTE1MjE1WhcNMzExMDI2MTE1MjE1WjCBljEL
				 *     MAkGA1UEBhMCUkIxDjAMBgNVBAgMBU1pbnNrMQ4wDAYDVQQHDAVNaW5zazEcMBoG
				 *     A1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDEiMCAGA1UEAwwZbGIuY29tcHV0ZWRl
				 *     di56YnkuaWNkYy5pbzElMCMGCSqGSIb3DQEJARYWYWhyZWNodXNoa2luQGdtYWls
				 *     LmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN9mILy9prFVniFz
				 *     WF/jXVa1GR1n+nw7aw3ck/xm8fW9v57IxWb/U/H41s14kGYdJqnK2abAcdgPpx4I
				 *     QSU0yYTOM6hfAB/Ueq0vMR3iOPEbm4h+52IMt60KARlRx623Eh/x5R7MSHygzTMF
				 *     xb72daRwbk56ScdUYQXon+ti+MExMVcpljVZqsauCr/wzDGQScu92qTPdUAyUpIj
				 *     z6l915l+lqLC3Ru0hU99Hg2Y/Y2be0KdzoQ+SnupaMVQ1l0jIN4xrJqQbKoEW4T0
				 *     7JZocFjQBxWR1Pgv30eoDTH7U9PsEPKwTuX6j5QyWXysy18ZOxIVknwqH+zkMjJh
				 *     1PJ4E5f4RXLnIZq9Y5W9Izlert5H8pdbNlPOCf8tq/6fYtgr6WLSR8Uc6bo/7+sP
				 *     d5VlpFcZ1Kso6s77Fqgm8pYk+B2cOtRHruygxdSuJvNNAigV3nlaz3yKcj1HF4GG
				 *     8fOE1bGDqjd7/JI7iG46d5ToKrLsvO4H4PGTVDUfWttUe95bxf1hq+wfzCsfE6xn
				 *     +IIr9oWojUxVg/+khCNiGqgQQQtj/nrsrrMM1C08DnfgW7o7LPn8sIr1COtJtDvZ
				 *     vTftkD7NC5KrZ1enlsZazeia+BOSgeAWRq1vG9tBq0ma/kPBdnJoYSul8g76vQO0
				 *     ZLhniWxzYBf4cYC9eAQHbN47zHNTAgMBAAGjZDBiMA8GA1UdEQQIMAaHBAr+FHww
				 *     HQYDVR0OBBYEFBOiEKwgqlSEoQbstblNl3tn9GMEMB8GA1UdIwQYMBaAFBOiEKwg
				 *     qlSEoQbstblNl3tn9GMEMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQAD
				 *     ggIBAMZMqxyH7Wvi0PMhAdMsBWZVhJDgvs8TahcmvFXa26awk8v014sTYix3SG7p
				 *     B32uNXsDji1D46Ys/2Qcp3NuCVFEUUFbYbKzTOptCjsuh3zIS2LiTPDWhRLYWv67
				 *     vfLpHxk5sDLhLyGp6B5X7WEQwpQcxvP3rd6R2t9O4ddPuCImz2lglKyGMYmPQPGU
				 *     oDIZ5F84+Bh2t973jT4wc+3ILvAL0GWKs6zjuOOgMm9JyLPaaxto10QsQfUdyXnx
				 *     7zC5EQQ9dkTf0qqSOxu/ZhoiTUIqpIfpZV1OF6X5BOlF6yVlyWB7v350y65+cMin
				 *     CcFTXuz29kFceMyNlBb2XEcPG2mNYq9Nl4SeEgKuSXrU6Su/eYjvpnElETIoJDLi
				 *     Q+LCtCu5+UyWLb5Zysx2iTyOuZgPVom/t00Knb4kEClQa0FKxV8/Mga59cp86ojO
				 *     1pU5moADBY7E/dD2ai74JZqmeN4aaEk/37zFbXEG4edPA5yawwj7yXk9GY9lj4VM
				 *     DqdN2HD8HpaSVCTaV58QGSfkzf4IPuYgbrcWeAxpGYL7M+eH89TlGPNsKnKCylSf
				 *     yUUbpg25KJJMhdY4D2mffl0izeJuJhyrNbtoQ6pfN2WlgSIixnFdVWUEYoSqXtPH
				 *     Uwa4MjwoCzcWU406lhDofkEB22lz4oeK9zXO3ubxR8aS7P8n
				 *     -----END CERTIFICATE----- */
				cert?: string;
				/** @example -----BEGIN PRIVATE KEY-----
				 *     MIIJRQIBADANBgkqhkiG9w0BAQEFAASCCS8wggkrAgEAAoICAQDfZiC8vaaxVZ4h
				 *     c1hf411WtRkdZ/p8O2sN3JP8ZvH1vb+eyMVm/1Px+NbNeJBmHSapytmmwHHYD6ce
				 *     CEElNMmEzjOoXwAf1HqtLzEd4jjxG5uIfudiDLetCgEZUcettxIf8eUezEh8oM0z
				 *     BcW+9nWkcG5OeknHVGEF6J/rYvjBMTFXKZY1WarGrgq/8MwxkEnLvdqkz3VAMlKS
				 *     I8+pfdeZfpaiwt0btIVPfR4NmP2Nm3tCnc6EPkp7qWjFUNZdIyDeMayakGyqBFuE
				 *     9OyWaHBY0AcVkdT4L99HqA0x+1PT7BDysE7l+o+UMll8rMtfGTsSFZJ8Kh/s5DIy
				 *     YdTyeBOX+EVy5yGavWOVvSM5Xq7eR/KXWzZTzgn/Lav+n2LYK+li0kfFHOm6P+/r
				 *     D3eVZaRXGdSrKOrO+xaoJvKWJPgdnDrUR67soMXUribzTQIoFd55Ws98inI9RxeB
				 *     hvHzhNWxg6o3e/ySO4huOneU6Cqy7LzuB+Dxk1Q1H1rbVHveW8X9YavsH8wrHxOs
				 *     Z/iCK/aFqI1MVYP/pIQjYhqoEEELY/567K6zDNQtPA534Fu6Oyz5/LCK9QjrSbQ7
				 *     2b037ZA+zQuSq2dXp5bGWs3omvgTkoHgFkatbxvbQatJmv5DwXZyaGErpfIO+r0D
				 *     tGS4Z4lsc2AX+HGAvXgEB2zeO8xzUwIDAQABAoICAQCgw2PnrysYDp7/P3xndL0k
				 *     uqpaKQtu/2tozEWKq6KPz37oC19TYYbNaN9bedmgQnYiViIPCAplC86dpB8NYVFr
				 *     yuAN2F/EiCnIG1/jO3ryt4VT0s88Fh7P3ZUw3VMuxcG7T14sraG0XhuNDihh5gZ+
				 *     0ZHv07zoPuabU+5RfCW7EWWKbhj0R5TH6VM/EVBAkq8oeXWwiMK98fjNxguY00Cl
				 *     6x0H/+cSGvScYVORQXmlwDARnnKRZCpBl4YYCLZay/7JJ0Io8KniJ8Sch40CKCJB
				 *     J2MRuKJkAD9T17G3OD/5D7aajxoYEhnk8d7IA6lOxF9oAjIqPD5BQW6GJzURUCv4
				 *     JhnL1hYZ5/TOZ8cI8cg2DSIlCEJsijstcMlPO6s3s58xvBzUfXieqUty8Ji5DrhT
				 *     yiUBWtNWHmkoVlXZmCyUz+sHMOG1++KzUFtr4cFxM/bO8sZDsto6bnIb+L4eijMz
				 *     oplSduOE3wxV7o2Jhhf/PZeOVOWqX/YVM4RwER5MZ+zh8KGwlN+BouBP+Pk6oKRB
				 *     wKakFno2WqmX8ZpVrHDITsK56qTvgwEXnrbanO3KINbqh1+HJrojkTlm95ltLhjo
				 *     k5FfVxeofWwexGWI9EhBYnclvi+mtKGim++QokSwTeyi8EVGj1we54f66ThI7xGE
				 *     SN8sD2gfeaQl7h9QFH00AQKCAQEA/dYVUOToJ0BofgQWvCfKANC4aopcc8IKiGZs
				 *     wZUPBooTwihGugr7rHopTV8GlBgAK1sfYlt+OOG8xZR/w6DJoeMS6BLdnekbovI8
				 *     3kmfCRR/LQz+7bmAfrdxwpi5yRNOvlytYJB8LGLKFA3Ro0QNKkVvya+98O6sXxwj
				 *     30PjVNmiS9k2vPU4+TepB/MWVRW1R7Y3dLdsqPrGf7cbvPxP7UyOCWIdPYYXUY9g
				 *     PBVmeQP61JsVhfzYq3cc3iCT1wXktS+0Pj1+QV0SBiVzkKwdIoFcFxKqI84E4Tcd
				 *     khrXO/p/0R++6GcJwbCRInXNqrh1Pcnrfq3Hfr2z6vNB2+LJAQKCAQEA4U2f9ljs
				 *     e3W5rd5lV36DuyxTERHQkh20geMogzegT69VV3S+gFPqJzvkXhRhT/jSoqaaGIrF
				 *     vxK9dhzaWGfQMRox2BvG8GcnkKKse1mrL2BzN328XaXDwnSnTdS3+nobLNgXY3bK
				 *     q6/V1YQAdOjgavuzSKse6XKsuwZt8/Z6E273qrT9EQbfjJS/nVSZAHltouBTt/Tb
				 *     Y37tPlmmtmTaCYT85LHqhWHDtsOcBfpyjdalH+MYDuiVDEWcCnM992S+DfKK4q0o
				 *     PfTadzj3sg/U/FOK7UAUgrONobhmbl1sOZggKQVEHPGRDXTIt+QSHdMmuYvxL9Jt
				 *     0URMK0Eiw71IUwKCAQEAzU4teXtbpfu7SEloVhDcmqI2tr1oH5yPRlmJl11HhOOD
				 *     LaPD6M/fVVaNN24ndPqgkHCoRrZ3tewm8au1VvYif5SZAynXI9SaLMY+ow/q2L5C
				 *     Sp7bRk2md1dKZLmAcvjx1JhDBvp15LSWe3fd2m69MzZsPzWsrEVvF5I8FWXkZgmM
				 *     8koistyokzIIvkxIANOJBxKDchy1f0st57ijb8ynnOgxbbd0rQFatPYBQTeR5Ulp
				 *     xDIXS4MBgFXb/HFfAihbHo0R/NFh3942KNB700TSX8k/Qc4v3LvSSJJ6kWSyN2nZ
				 *     nbxOfcxxIL799GBR08ZT1YEOvywxUfp/ngXYe8/HAQKCAQEAvq8/InVyeK9Tnmcq
				 *     qFmITmMeTsUgHHqNqpzCTgRHZwnDFgjVrrDW7avQBRwEnHXAeC6/HuRcpvHKbmvP
				 *     FKGQX+6GnxwrTI5RuyUjDCcBLlDYUu/U/AFu5GZsrv/JUnIEC/k8Gk+RCqwAM/zL
				 *     kicCwSkUPP2vZO9MZ+HyL1e9TDNP5CfYQ4/opgfDAPp3oCIle4OW94uCHvxu+KVR
				 *     5u8GZqYqj7hQ/+CVj1qQ87JbP9aZ3JoMY5nPhBpqDaIpoPefrxhHGcBp3b4dJGiP
				 *     oyGpJoHihBgHA/PJfEUgVGo3TauGFJHDaye8l4Hu20xpVNq/3KwnTk0v6rx+JuGy
				 *     9a1+xwKCAQEAvd/zRbG/pct1lhrFQNm0crbjGN4H4wzKpHjo6F4jUr9556RGzNWU
				 *     mhPiuz2u6HKKMhsI3ktkmUiNhOvsfde/U0fl+CE4pvluAvwIQBeY82h3kRLtcw7p
				 *     xwCMXrcM9bjt41wQpO31E3bdKnR9bbO+A9UDtmOsIzfl08NtYAUkc7jgNIr7RqCE
				 *     HTUIhv6o6OEumEYhDDKVy5OMOE6mcb0GX7801LD0b0zjxI/6HMMDa9iytNU+rg8l
				 *     0jfPHTl3rMqyRN9tDY+lzQEQJnnFUG6a4FiNdutdrg0J78DHoRRUClufIcvUvpPr
				 *     5ABeDQkqJFWJyTPhLw5Io3QZaLecpXxvxA==
				 *     -----END PRIVATE KEY-----
				 *      */
				key?: string;
				/** @example  */
				ca?: string;
				/** @example  */
				dest_ca?: string;
				hostnames?: unknown[];
				/** @example 2021-10-28T11:52:15.000Z */
				valid_from?: string;
				/** @example 2031-10-26T11:52:15.000Z */
				valid_until?: string;
				/** @example Default Company Ltd */
				issuer?: string;
			};
		};
		Certificate_POST: {
			/** @example lb.computedev.loc.icdc.io */
			name?: string;
			/** @example -----BEGIN CERTIFICATE-----
			 *     MIIGIDCCBAigAwIBAgIUMzFmSJ1zWSys9mqGaK8yjOpXffcwDQYJKoZIhvcNAQEL
			 *     BQAwgZYxCzAJBgNVBAYTAlJCMQ4wDAYDVQQIDAVNaW5zazEOMAwGA1UEBwwFTWlu
			 *     c2sxHDAaBgNVBAoME0RlZmF1bHQgQ29tcGFueSBMdGQxIjAgBgNVBAMMGWxiLmNv
			 *     bXB1dGVkZXYuemJ5LmljZGMuaW8xJTAjBgkqhkiG9w0BCQEWFmFocmVjaHVzaGtp
			 *     bkBnbWFpbC5jb20wHhcNMjExMDI4MTE1MjE1WhcNMzExMDI2MTE1MjE1WjCBljEL
			 *     MAkGA1UEBhMCUkIxDjAMBgNVBAgMBU1pbnNrMQ4wDAYDVQQHDAVNaW5zazEcMBoG
			 *     A1UECgwTRGVmYXVsdCBDb21wYW55IEx0ZDEiMCAGA1UEAwwZbGIuY29tcHV0ZWRl
			 *     di56YnkuaWNkYy5pbzElMCMGCSqGSIb3DQEJARYWYWhyZWNodXNoa2luQGdtYWls
			 *     LmNvbTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAN9mILy9prFVniFz
			 *     WF/jXVa1GR1n+nw7aw3ck/xm8fW9v57IxWb/U/H41s14kGYdJqnK2abAcdgPpx4I
			 *     QSU0yYTOM6hfAB/Ueq0vMR3iOPEbm4h+52IMt60KARlRx623Eh/x5R7MSHygzTMF
			 *     xb72daRwbk56ScdUYQXon+ti+MExMVcpljVZqsauCr/wzDGQScu92qTPdUAyUpIj
			 *     z6l915l+lqLC3Ru0hU99Hg2Y/Y2be0KdzoQ+SnupaMVQ1l0jIN4xrJqQbKoEW4T0
			 *     7JZocFjQBxWR1Pgv30eoDTH7U9PsEPKwTuX6j5QyWXysy18ZOxIVknwqH+zkMjJh
			 *     1PJ4E5f4RXLnIZq9Y5W9Izlert5H8pdbNlPOCf8tq/6fYtgr6WLSR8Uc6bo/7+sP
			 *     d5VlpFcZ1Kso6s77Fqgm8pYk+B2cOtRHruygxdSuJvNNAigV3nlaz3yKcj1HF4GG
			 *     8fOE1bGDqjd7/JI7iG46d5ToKrLsvO4H4PGTVDUfWttUe95bxf1hq+wfzCsfE6xn
			 *     +IIr9oWojUxVg/+khCNiGqgQQQtj/nrsrrMM1C08DnfgW7o7LPn8sIr1COtJtDvZ
			 *     vTftkD7NC5KrZ1enlsZazeia+BOSgeAWRq1vG9tBq0ma/kPBdnJoYSul8g76vQO0
			 *     ZLhniWxzYBf4cYC9eAQHbN47zHNTAgMBAAGjZDBiMA8GA1UdEQQIMAaHBAr+FHww
			 *     HQYDVR0OBBYEFBOiEKwgqlSEoQbstblNl3tn9GMEMB8GA1UdIwQYMBaAFBOiEKwg
			 *     qlSEoQbstblNl3tn9GMEMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQAD
			 *     ggIBAMZMqxyH7Wvi0PMhAdMsBWZVhJDgvs8TahcmvFXa26awk8v014sTYix3SG7p
			 *     B32uNXsDji1D46Ys/2Qcp3NuCVFEUUFbYbKzTOptCjsuh3zIS2LiTPDWhRLYWv67
			 *     vfLpHxk5sDLhLyGp6B5X7WEQwpQcxvP3rd6R2t9O4ddPuCImz2lglKyGMYmPQPGU
			 *     oDIZ5F84+Bh2t973jT4wc+3ILvAL0GWKs6zjuOOgMm9JyLPaaxto10QsQfUdyXnx
			 *     7zC5EQQ9dkTf0qqSOxu/ZhoiTUIqpIfpZV1OF6X5BOlF6yVlyWB7v350y65+cMin
			 *     CcFTXuz29kFceMyNlBb2XEcPG2mNYq9Nl4SeEgKuSXrU6Su/eYjvpnElETIoJDLi
			 *     Q+LCtCu5+UyWLb5Zysx2iTyOuZgPVom/t00Knb4kEClQa0FKxV8/Mga59cp86ojO
			 *     1pU5moADBY7E/dD2ai74JZqmeN4aaEk/37zFbXEG4edPA5yawwj7yXk9GY9lj4VM
			 *     DqdN2HD8HpaSVCTaV58QGSfkzf4IPuYgbrcWeAxpGYL7M+eH89TlGPNsKnKCylSf
			 *     yUUbpg25KJJMhdY4D2mffl0izeJuJhyrNbtoQ6pfN2WlgSIixnFdVWUEYoSqXtPH
			 *     Uwa4MjwoCzcWU406lhDofkEB22lz4oeK9zXO3ubxR8aS7P8n
			 *     -----END CERTIFICATE----- */
			cert?: string;
			/** @example -----BEGIN PRIVATE KEY-----
			 *     MIIJRQIBADANBgkqhkiG9w0BAQEFAASCCS8wggkrAgEAAoICAQDfZiC8vaaxVZ4h
			 *     c1hf411WtRkdZ/p8O2sN3JP8ZvH1vb+eyMVm/1Px+NbNeJBmHSapytmmwHHYD6ce
			 *     CEElNMmEzjOoXwAf1HqtLzEd4jjxG5uIfudiDLetCgEZUcettxIf8eUezEh8oM0z
			 *     BcW+9nWkcG5OeknHVGEF6J/rYvjBMTFXKZY1WarGrgq/8MwxkEnLvdqkz3VAMlKS
			 *     I8+pfdeZfpaiwt0btIVPfR4NmP2Nm3tCnc6EPkp7qWjFUNZdIyDeMayakGyqBFuE
			 *     9OyWaHBY0AcVkdT4L99HqA0x+1PT7BDysE7l+o+UMll8rMtfGTsSFZJ8Kh/s5DIy
			 *     YdTyeBOX+EVy5yGavWOVvSM5Xq7eR/KXWzZTzgn/Lav+n2LYK+li0kfFHOm6P+/r
			 *     D3eVZaRXGdSrKOrO+xaoJvKWJPgdnDrUR67soMXUribzTQIoFd55Ws98inI9RxeB
			 *     hvHzhNWxg6o3e/ySO4huOneU6Cqy7LzuB+Dxk1Q1H1rbVHveW8X9YavsH8wrHxOs
			 *     Z/iCK/aFqI1MVYP/pIQjYhqoEEELY/567K6zDNQtPA534Fu6Oyz5/LCK9QjrSbQ7
			 *     2b037ZA+zQuSq2dXp5bGWs3omvgTkoHgFkatbxvbQatJmv5DwXZyaGErpfIO+r0D
			 *     tGS4Z4lsc2AX+HGAvXgEB2zeO8xzUwIDAQABAoICAQCgw2PnrysYDp7/P3xndL0k
			 *     uqpaKQtu/2tozEWKq6KPz37oC19TYYbNaN9bedmgQnYiViIPCAplC86dpB8NYVFr
			 *     yuAN2F/EiCnIG1/jO3ryt4VT0s88Fh7P3ZUw3VMuxcG7T14sraG0XhuNDihh5gZ+
			 *     0ZHv07zoPuabU+5RfCW7EWWKbhj0R5TH6VM/EVBAkq8oeXWwiMK98fjNxguY00Cl
			 *     6x0H/+cSGvScYVORQXmlwDARnnKRZCpBl4YYCLZay/7JJ0Io8KniJ8Sch40CKCJB
			 *     J2MRuKJkAD9T17G3OD/5D7aajxoYEhnk8d7IA6lOxF9oAjIqPD5BQW6GJzURUCv4
			 *     JhnL1hYZ5/TOZ8cI8cg2DSIlCEJsijstcMlPO6s3s58xvBzUfXieqUty8Ji5DrhT
			 *     yiUBWtNWHmkoVlXZmCyUz+sHMOG1++KzUFtr4cFxM/bO8sZDsto6bnIb+L4eijMz
			 *     oplSduOE3wxV7o2Jhhf/PZeOVOWqX/YVM4RwER5MZ+zh8KGwlN+BouBP+Pk6oKRB
			 *     wKakFno2WqmX8ZpVrHDITsK56qTvgwEXnrbanO3KINbqh1+HJrojkTlm95ltLhjo
			 *     k5FfVxeofWwexGWI9EhBYnclvi+mtKGim++QokSwTeyi8EVGj1we54f66ThI7xGE
			 *     SN8sD2gfeaQl7h9QFH00AQKCAQEA/dYVUOToJ0BofgQWvCfKANC4aopcc8IKiGZs
			 *     wZUPBooTwihGugr7rHopTV8GlBgAK1sfYlt+OOG8xZR/w6DJoeMS6BLdnekbovI8
			 *     3kmfCRR/LQz+7bmAfrdxwpi5yRNOvlytYJB8LGLKFA3Ro0QNKkVvya+98O6sXxwj
			 *     30PjVNmiS9k2vPU4+TepB/MWVRW1R7Y3dLdsqPrGf7cbvPxP7UyOCWIdPYYXUY9g
			 *     PBVmeQP61JsVhfzYq3cc3iCT1wXktS+0Pj1+QV0SBiVzkKwdIoFcFxKqI84E4Tcd
			 *     khrXO/p/0R++6GcJwbCRInXNqrh1Pcnrfq3Hfr2z6vNB2+LJAQKCAQEA4U2f9ljs
			 *     e3W5rd5lV36DuyxTERHQkh20geMogzegT69VV3S+gFPqJzvkXhRhT/jSoqaaGIrF
			 *     vxK9dhzaWGfQMRox2BvG8GcnkKKse1mrL2BzN328XaXDwnSnTdS3+nobLNgXY3bK
			 *     q6/V1YQAdOjgavuzSKse6XKsuwZt8/Z6E273qrT9EQbfjJS/nVSZAHltouBTt/Tb
			 *     Y37tPlmmtmTaCYT85LHqhWHDtsOcBfpyjdalH+MYDuiVDEWcCnM992S+DfKK4q0o
			 *     PfTadzj3sg/U/FOK7UAUgrONobhmbl1sOZggKQVEHPGRDXTIt+QSHdMmuYvxL9Jt
			 *     0URMK0Eiw71IUwKCAQEAzU4teXtbpfu7SEloVhDcmqI2tr1oH5yPRlmJl11HhOOD
			 *     LaPD6M/fVVaNN24ndPqgkHCoRrZ3tewm8au1VvYif5SZAynXI9SaLMY+ow/q2L5C
			 *     Sp7bRk2md1dKZLmAcvjx1JhDBvp15LSWe3fd2m69MzZsPzWsrEVvF5I8FWXkZgmM
			 *     8koistyokzIIvkxIANOJBxKDchy1f0st57ijb8ynnOgxbbd0rQFatPYBQTeR5Ulp
			 *     xDIXS4MBgFXb/HFfAihbHo0R/NFh3942KNB700TSX8k/Qc4v3LvSSJJ6kWSyN2nZ
			 *     nbxOfcxxIL799GBR08ZT1YEOvywxUfp/ngXYe8/HAQKCAQEAvq8/InVyeK9Tnmcq
			 *     qFmITmMeTsUgHHqNqpzCTgRHZwnDFgjVrrDW7avQBRwEnHXAeC6/HuRcpvHKbmvP
			 *     FKGQX+6GnxwrTI5RuyUjDCcBLlDYUu/U/AFu5GZsrv/JUnIEC/k8Gk+RCqwAM/zL
			 *     kicCwSkUPP2vZO9MZ+HyL1e9TDNP5CfYQ4/opgfDAPp3oCIle4OW94uCHvxu+KVR
			 *     5u8GZqYqj7hQ/+CVj1qQ87JbP9aZ3JoMY5nPhBpqDaIpoPefrxhHGcBp3b4dJGiP
			 *     oyGpJoHihBgHA/PJfEUgVGo3TauGFJHDaye8l4Hu20xpVNq/3KwnTk0v6rx+JuGy
			 *     9a1+xwKCAQEAvd/zRbG/pct1lhrFQNm0crbjGN4H4wzKpHjo6F4jUr9556RGzNWU
			 *     mhPiuz2u6HKKMhsI3ktkmUiNhOvsfde/U0fl+CE4pvluAvwIQBeY82h3kRLtcw7p
			 *     xwCMXrcM9bjt41wQpO31E3bdKnR9bbO+A9UDtmOsIzfl08NtYAUkc7jgNIr7RqCE
			 *     HTUIhv6o6OEumEYhDDKVy5OMOE6mcb0GX7801LD0b0zjxI/6HMMDa9iytNU+rg8l
			 *     0jfPHTl3rMqyRN9tDY+lzQEQJnnFUG6a4FiNdutdrg0J78DHoRRUClufIcvUvpPr
			 *     5ABeDQkqJFWJyTPhLw5Io3QZaLecpXxvxA==
			 *     -----END PRIVATE KEY-----
			 *      */
			key?: string;
			/** @example  */
			ca?: string;
			/** @example  */
			dest_ca?: string;
			/** @example user@test.email */
			owner?: string;
		};
		ServiceCollection: components["schemas"]["Service"][];
		Service: {
			/** @example 1 */
			id?: number;
			/** @example Clone#59 */
			name?: string;
			/** @example 26000000000113 */
			ext_id?: string;
			/** @example 10.254.20.65,fe80::f1d6:c354:43f5:b643 */
			ipaddresses?: string;
			/** @example user@test.email */
			owner?: string;
			/** @example icdc */
			account?: string;
		};
		RouteCollection: components["schemas"]["Route"][];
		Route: {
			route: {
				/** @example 1 */
				readonly id?: number;
				/** @example Route */
				name?: string;
				/** @example test.loc.icdc.io */
				hostname?: string;
				/** @example / */
				path?: string;
				/** @example 6587 */
				target_port?: number;
				/** @example None */
				insecure?: string;
				/** @example Edge */
				tls_termination?: string;
				/** @example KV */
				labels?: string;
				/** @example 1 */
				cloud_gateway_id?: number;
				/** @example 1 */
				certificate_id?: number;
				/** @example tcp */
				source_proto?: string;
				/** @example tcp */
				destination_proto?: string;
				/** @example 4 */
				ip_version?: number;
				/** @example user@test.email */
				owner?: string;
				services?: components["schemas"]["Service"][];
				routes_services?: {
					balance_type: string;
					created_at: string;
					id: number;
					name: string;
					route_id: number;
					service_id: number;
					updated_at: string;
					value: number;
				}[];
				/** @example true */
				healthcheck_enabled?: boolean;
				cloud_gateway: {
					account: string;
					cloudgw_id: string;
					cloudgw_instance: string;
					created_at: string;
					id: number;
					name: string;
					updated_at: string;
				};
				healthcheck?: {
					/** @example / */
					path?: string;
					/** @example https */
					scheme?: string;
					/** @example check-cors.loc.icdc.io */
					hostname?: string;
					/** @example 8080 */
					port?: number;
					/** @example 15 */
					interval?: number;
					/** @example 3 */
					timeout?: number;
					/** @example {
					 *       "x-icdc-account": "devel",
					 *       "x-icdc-role": "admin"
					 *     } */
					headers?: Record<string, string>;
					/** @example POST */
					method?: string;
					/** @example true */
					follow_redirects?: boolean;
				};
			};
		};
		Route_POST: {
			route: Omit<components["schemas"]["Route"]["route"], "cloud_gateway">;
		};
	};
	responses: {
		/** @description This API gateway error means selected operation is not supported */
		apigw_not_allowed: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": string;
			};
		};
		/** @description Server error. */
		server_error: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["error"];
			};
		};
		/** @description Request is not authorized, usually because of: bad credentials, expired JWT token, account role is not assigned to authenticated user.
		 *      */
		unauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["error"];
			};
		};
		/** @description Request authorized, but current user doesn't have access rights to perform action.
		 *      */
		forbidden: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["error"];
			};
		};
		/** @description Requested object is not found
		 *      */
		not_found: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["error"];
			};
		};
		/** @description Unprocessable entity.
		 *      */
		unprocessable_entity: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["error"];
			};
		};
		/** @description A list of ALB Gateways attached to account's infrastructure */
		alb_list: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["GatewayCollection"];
			};
		};
	};
	parameters: {
		/** @description Name of the account (5-character string) */
		Account: string;
		/** @description Role name */
		Role: string;
		/** @description Used for simplified authorization for some internal requests from CloudGateway to config.
		 *      */
		CloudGatewayId: string;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	alb_list: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			200: components["responses"]["alb_list"];
			401: components["responses"]["unauthorized"];
			500: components["responses"]["server_error"];
		};
	};
	alb_attach: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": {
					/** @example alb-default */
					name?: string;
					/** @example a843bf2a-7353-563e-a220-f59949849dba */
					cloudgw_id?: string;
					/** @example acc */
					account?: string;
				};
			};
		};
		responses: {
			200: components["responses"]["alb_list"];
			401: components["responses"]["unauthorized"];
			405: components["responses"]["apigw_not_allowed"];
			422: components["responses"]["unprocessable_entity"];
		};
	};
	alb_show: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Gateway"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			500: components["responses"]["server_error"];
		};
	};
	alb_modify: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Gateway_PUT"];
			};
		};
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Gateway"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			422: components["responses"]["unprocessable_entity"];
			500: components["responses"]["server_error"];
		};
	};
	alb_unregister: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			500: components["responses"]["server_error"];
		};
	};
	certificates_list: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CertificateCollection"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			500: components["responses"]["server_error"];
		};
	};
	certificates_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["Certificate_POST"];
			};
		};
		responses: {
			/** @description created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Certificate"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			422: components["responses"]["unprocessable_entity"];
			500: components["responses"]["server_error"];
		};
	};
	certificate_show: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Unique ID of certificate */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Certificate"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			500: components["responses"]["server_error"];
		};
	};
	certificate_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Unique ID of certificate */
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Certificate_POST"];
			};
		};
		responses: {
			/** @description operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Certificate"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			422: components["responses"]["unprocessable_entity"];
			500: components["responses"]["server_error"];
		};
	};
	certificate_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Unique ID of certificate */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			500: components["responses"]["server_error"];
		};
	};
	services_list: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ServiceCollection"];
				};
			};
			401: components["responses"]["unauthorized"];
			500: components["responses"]["server_error"];
		};
	};
	routes_list: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["RouteCollection"];
				};
			};
			401: components["responses"]["unauthorized"];
			500: components["responses"]["server_error"];
		};
	};
	route_create: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Route"];
			};
		};
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Route"];
				};
			};
			401: components["responses"]["unauthorized"];
			422: components["responses"]["unprocessable_entity"];
			500: components["responses"]["server_error"];
		};
	};
	route_show: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Route"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			500: components["responses"]["server_error"];
		};
	};
	route_update: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id: number;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Route"];
			};
		};
		responses: {
			/** @description Operation successful */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Route"];
				};
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			422: components["responses"]["unprocessable_entity"];
			500: components["responses"]["server_error"];
		};
	};
	route_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				/** @description Unique ID of route */
				id: number;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description No content */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			401: components["responses"]["unauthorized"];
			403: components["responses"]["forbidden"];
			404: components["responses"]["not_found"];
			500: components["responses"]["server_error"];
		};
	};
}
